// src/userData.js
export const users = [
    { name: "농협손해보험", url: "https://www.nhfire.co.kr/announce/productAnnounce/applicableInterestRateAnnounce.nhfire", column: "left" },
    { name: "롯데손해보험", url: "https://www.lotteins.co.kr/web/C/D/H/cdh210.jsp", column: "left" },
    { name: "라이나손해보험", url: "https://www.chubb.com/kr-kr/disclosure/interest-rate-disclosure.html", column: "left" },
    { name: "메리츠화재", url: "https://www.meritzfire.com/disclosure/product-announcement/interest-rate.do#!/", column: "left" },
    { name: "삼성화재", url: "https://www.samsungfire.com/vh/page/VH.HPIF0104.do", column: "left" },
    { name: "신한EZ손해보험", url: "https://www.shinhanez.co.kr/static/pub/PUB20020T03.html", column: "left" },
    { name: "하나손해보험", url: "https://www.hanainsure.co.kr/w/disclosure/product/rateProduct", column: "left" },
    { name: "한화손해보험", url: "https://www.hwgeneralins.com/notice/ir/product-ratio.do", column: "left" },
    { name: "현대해상", url: "https://www.hi.co.kr/serviceAction.do?view=bin/PA/03/HHPA03010M", column: "left" },
    { name: "흥국화재", url: "https://www.heungkukfire.co.kr/FRW/announce/goodsApplyInterestList.do", column: "left" },
    { name: "캐롯손해보험", url: "https://www.hwgeneralins.com/notice/ir/product-ratio.do", column: "left" },
    { name: "AIG손해보험", url: "https://www.aig.co.kr/wo/dpwot006.html?menuId=MS703", column: "left" },
    { name: "AXA손해보험", url: "https://www.axa.co.kr/AsianPlatformInternet/html/axacms/common/intro/disclosure/insurance/index.html#CatIDsb13_73646", column: "left" },
    { name: "DB손해보험", url: "https://www.idbins.com/pc/bizxpress/contentTemplet/pb/ppb/ap/mon.jsp", column: "left" },
    { name: "KB손해보험", url: "https://www.kbinsure.co.kr/CG802060001.ec", column: "left" },
    { name: "MG손해보험", url: "https://www.yebyeol.co.kr/PB031080DM.scp?menuId=MN0803003", column: "left" },
    { name: "교보생명", url: "https://www.kyobo.com/dgt/web/disclosure/interest-rate-disclosure/this-month", column: "right" },
    { name: "교보플래닛", url: "https://www.lifeplanet.co.kr/disclosure/good/HPDA41S0.dev", column: "right" },
    { name: "농협생명", url: "https://www.nhlife.co.kr/ho/on/HOON0038M00.nhl", column: "right" },
    { name: "동양생명", url: "https://pbano.myangel.co.kr/notice/rate/WE_PA_AP_09_01_00.jsp", column: "right" },
    { name: "라이나생명", url: "https://www.lina.co.kr/disclosure/product-public-announcement/applied-interest-rate", column: "right" },
    { name: "메트라이프", url: "https://brand.metlife.co.kr/pn/tsmmInttr/retrieveTsmmInttrMain.do?", column: "right" },
    { name: "미래에셋생명", url: "https://life.miraeasset.com/micro/disclosure/product/applyinterest/PC-HO-080403-010000.do", column: "right" },
    { name: "삼성생명", url: "https://www.samsunglife.com/individual/products/disclosure/insurate/PDO-PRPRR012100M", column: "right" },
    { name: "신한라이프", url: "https://www.shinhanlife.co.kr/hp/cdhi0250t01.do", column: "right" },
    { name: "처브라이프", url: "https://www.chubblife.co.kr/front/official/sale/listRate.do", column: "right" },
    { name: "푸르덴셜생명", url: "https://www.kblife.co.kr/customer-common/appliedInterestRate.do", column: "right" },
    { name: "푸본현대", url: "https://www.fubonhyundai.com/#CUSI150103010000", column: "right" },
    { name: "하나생명", url: "https://hanalife.co.kr/anm/interestRate/interestRate_tab1_7.do", column: "right" },
    { name: "한화생명", url: "https://www.hanwhalife.com/main/disclosure/goods/disclosurenotice/DF_GDDN000_P10000.do?MENU_ID1=DF_GDAR000#none", column: "right" },
    { name: "흥국생명", url: "https://www.heungkuklife.co.kr/front/public/publicRate10.do?rateType=R010", column: "right" },
    { name: "ABL생명", url: "https://www.abllife.co.kr/st/pban/prdtPban/pbanlrt/pbanlrt1/pbanlrt11?page=index", column: "right" },
    { name: "AIA생명", url: "https://mypage.aia.co.kr/AIAHomepage/disclosure/our-products/interest-rate/interest-rate-linked.do", column: "right" },
    { name: "DB생명", url: "https://www.idblife.com/notice/product/tmo_int", column: "right" },
    { name: "IBK연금", url: "https://www.ibki.co.kr/process/HP_THMM_RITR_PBANO_RITR", column: "right" },
    { name: "IM라이프", url: "https://www.imlifeins.co.kr/BA/BA_A130.do", column: "right" },
    { name: "KB라이프", url: "https://www.kblife.co.kr/customer-common/appliedInterestRate.do", column: "right" },
    { name: "KDB생명", url: "https://www.kdblife.co.kr/ajax.do?scrId=HDLMA002M08P", column: "right" },
    
    
];
